"""My first migration

Revision ID: c356b329f9b8
Revises: 
Create Date: 2021-09-02 22:28:39.928957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c356b329f9b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(255), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('modicum', sa.Integer(), nullable=True),
    sa.Column('on_hold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_detail_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('food_plate_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('served', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_plate_id'], ['food_plate.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['orders_id'], ['orders_completed.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies_plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('food_plate_id', sa.Integer(), nullable=True),
    sa.Column('supplies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_plate_id'], ['food_plate.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['supplies_id'], ['supplies.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('email', sa.String(255), nullable=True),
    sa.Column('password', sa.String(255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['reservation_status.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['orders_status.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('food_plate_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('served', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_plate_id'], ['food_plate.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_detail')
    op.drop_table('orders')
    op.drop_table('tables')
    op.drop_table('reservation')
    op.drop_table('user')
    op.drop_table('supplies_plate')
    op.drop_table('orders_detail_completed')
    op.drop_table('supplies')
    op.drop_table('rol')
    op.drop_table('reservation_status')
    op.drop_table('orders_status')
    op.drop_table('orders_completed')
    op.drop_table('food_plate')
    # ### end Alembic commands ###
